---
- name: Install systemd-timesyncd
  ansible.builtin.package:
    name: "systemd-timesyncd"
    state: present

- name: Set TimeZone
  community.general.timezone:
    name: "{{ ntp_time_zone }}"

- name: Copy configurations file
  ansible.builtin.template:
    src: timesyncd.conf.j2
    dest: "/etc/systemd/timesyncd.conf"
    owner: root
    group: root
    mode: "0644"
  register: ntp_config_change
  notify:
    - Set NTP Sync
    - Restart timesyncd
